# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d416f8b1c1ecca004ec50dddf9c553e2c8b07f7aa58a46683af1dfae17dc2bce0aaa746d1bd3de39bd6ca13416559b2499aeebf89e820d46dcfb451374f38f4

test:
  secret_key_base: f4e1ff5b882ce43f39e9c32d3390e80f0ec2c8c52b59fd2ba7a15ed0385864bcd3bb5dedcca00f80889c8fde49239416751b30f60df965736967af727377f10e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
